### ISSUE TITLE
sharing location from/to EVMap not working correctly

### ISSUE THREAD

**Issue by clyso** [johan12345/EVMap#79]
I'm having troubles to share location to and from EVMap:
- when I try to share a charging station from EVMap to Tesla App I get an Error in the Tesla App ( Something went wrong - please try again later ). Sharing from e.g. Google Maps to Tesla App works as expected. Using the directions Button in EVMap opens directly in Google Maps and works as expected
- when I try to share a Location from my calendar app - acalender+ - to EVMap it works but I get to a completely different location (e.g. Location in Germany is shown in EVMap somewhere in USA). sharing the exact same location from calendar app to Tesla App or Google Maps works as expected
Would be really nice if at least the sharing to the Tesla App works :) Otherwise great App!

**Comment by johan12345** [comment]
Thanks for reporting these issues!

> when I try to share a charging station from EVMap to Tesla App I get an Error in the Tesla App ( Something went wrong - please try again later ). Sharing from e.g. Google Maps to Tesla App works as expected. Using the directions Button in EVMap opens directly in Google Maps and works as expected

Have you used the sharing button in the top right of EVMap (which shares a link to GoingElectric.de - Tesla probably cannot handle that) or tapped on the location coordinates further down in the details? Alternatively, you could also try disabling the "Start navigation immediately" option in EVMap's settings and then using the directions button.

Unfortunately, I cannot test with the Tesla app myself, I am just a Zoe owner 😉 

> when I try to share a Location from my calendar app - acalender+ - to EVMap it works but I get to a completely different location (e.g. Location in Germany is shown in EVMap somewhere in USA). sharing the exact same location from calendar app to Tesla App or Google Maps works as expected

I found that aCalendar shares the location only as a text (e.g. "Berlin, Germany") and not with geographic coordinates. In 36a702a6, I adjusted EVMap so that these can now also be handled, as long as Android's default Geocoder can resolve them.

**Comment by clyso** [comment]
> Thanks for reporting these issues!
> 
> > when I try to share a charging station from EVMap to Tesla App I get an Error in the Tesla App ( Something went wrong - please try again later ). Sharing from e.g. Google Maps to Tesla App works as expected. Using the directions Button in EVMap opens directly in Google Maps and works as expected
> 
> Have you used the sharing button in the top right of EVMap (which shares a link to GoingElectric.de - Tesla probably cannot handle that) or tapped on the location coordinates further down in the details? Alternatively, you could also try disabling the "Start navigation immediately" option in EVMap's settings and then using the directions button.
> 
> Unfortunately, I cannot test with the Tesla app myself, I am just a Zoe owner 😉

my fault - when tapping on coordinates or using directions button with "Start navigation immediately" disabled it works with the Tesla app as expected 👍 

> > when I try to share a Location from my calendar app - acalender+ - to EVMap it works but I get to a completely different location (e.g. Location in Germany is shown in EVMap somewhere in USA). sharing the exact same location from calendar app to Tesla App or Google Maps works as expected
> 
> I found that aCalendar shares the location only as a text (e.g. "Berlin, Germany") and not with geographic coordinates. In [36a702a](https://github.com/johan12345/EVMap/commit/36a702a6f44a7fe8b6970dc5a7242be86d4849b2), I adjusted EVMap so that these can now also be handled, as long as Android's default Geocoder can resolve them.

I will test as soon as a new version including the fix is released.
thank you very much for the fast support and this wonderful app - very appreciated 👍

**Comment by johan12345** [comment]
Ah, thanks!
The fixes are included in the update 0.7.1, which should appear in the next few hours. If something is still not working, please reopen :)
